import turtle as t
def changeposition(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
def tree():
    t.color("saddlebrown")
    t.width(5)
    t.begin_fill()
    t.left(90)
    t.forward(70)
    t.right(90)
    t.begin_fill()
    t.color("forestgreen")
    t.circle(40)
    t.end_fill()
def bird():
    t.color("black")
    t.left(45)
    t.forward(40)
    t.left(180)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.left(180)
    t.forward(40)
    t.left(45)
def hmarka():
    t.color("grey80")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    changeposition(-70,300)
    t.color("grey80")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    changeposition(-40,280)
    t.color("grey80")
    t.begin_fill()
    t.circle(30)
    t.end_fill()

def pyramid(color,length):
    t.color(color)
    t.begin_fill()
    t.right(120)
    t.forward(length)
    t.left(120)
    t.forward(length)
    t.left(120)
    t.forward(length)
    t.end_fill()
def sky():
    t.color("lightblue")
    t.begin_fill()
    changeposition(-765, -385)
    t.forward(1525)
    t.left(90)
    t.forward(780)
    t.left(90)
    t.forward(1525)
    t.left(90)
    t.forward(780)
    t.end_fill()
    changeposition(0, -50)
    t.color("antiquewhite")
    t.begin_fill()
    t.right(90)
    t.forward(765)
    t.left(90)
    t.forward(335)
    t.left(90)
    t.forward(1525)
    t.left(90)
    t.forward(335)
    t.left(90)
    t.forward(1525)
    t.end_fill()