import turtle as t
#
# t.penup()
# t.goto(-375,-315)
# t.pendown()
# t.done()

# t.color("blue","yellow")
# t.begin_fill()
# t.width(10)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.end_fill()
# t.done()

# t.color("black")
# t.circle(75)
# t.penup()
# t.goto(-150,0)
# t.pendown()
# t.color("blue")
# t.circle(75)
# t.penup()
# t.goto(150,0)
# t.pendown()
# t.color("red")
# t.circle(75)
# t.penup()
# t.goto(-75,-75)
# t.pendown()
# t.color("yellow")
# t.circle(75)
# t.penup()
# t.goto(75,-75)
# t.pendown()
# t.color("green")
# t.circle(75)
#
# t.done()